<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ben Rochford">

<title>HW9</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="HW9_files/libs/clipboard/clipboard.min.js"></script>
<script src="HW9_files/libs/quarto-html/quarto.js"></script>
<script src="HW9_files/libs/quarto-html/popper.min.js"></script>
<script src="HW9_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="HW9_files/libs/quarto-html/anchor.min.js"></script>
<link href="HW9_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="HW9_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="HW9_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="HW9_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="HW9_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">HW9</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ben Rochford </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="hw9" class="level2">
<h2 class="anchored" data-anchor-id="hw9">HW9</h2>
<p>Setup</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.3     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WeightIt)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cobalt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code> cobalt (Version 4.5.3, Build Date: 2024-01-09)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(marginaleffects)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modelsummary)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gssr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Package loaded. To attach the GSS data, type data(gss_all) at the console.
For the codebook, type data(gss_dict).
For the panel data and documentation, type e.g. data(gss_panel08_long) and data(gss_panel_doc).
For help on a specific GSS variable, type ?varname at the console.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>gss2022 <span class="ot">&lt;-</span> <span class="fu">gss_get_yr</span>(<span class="dv">2022</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Fetching: https://gss.norc.org/documents/stata/2022_stata.zip</code></pre>
</div>
</div>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section">9.1.1</h3>
<p>Choose one outcome variable and one “treatment” variable</p>
<p>Let’s do <strong>POLVIEWS</strong> as treatment, and <strong>LETIN1A</strong> as outcome.</p>
<p><em>(also interesting: NOTSMART, AFRAIDOF, INCOM16, MADEG)</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>gss2022<span class="sc">$</span>polviews[<span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;labelled&lt;double&gt;[0]&gt;: think of self as liberal or conservative

Labels:
 value                         label
     1             extremely liberal
     2                       liberal
     3              slightly liberal
     4  moderate, middle of the road
     5         slightly conservative
     6                  conservative
     7        extremely conservative
 NA(d)                    don't know
 NA(i)                           iap
 NA(j)            I don't have a job
 NA(m)                   dk, na, iap
 NA(n)                     no answer
 NA(p)                 not imputable
 NA(q)                 not imputable
 NA(r)                       refused
 NA(s)                skipped on web
 NA(u)                    uncodeable
 NA(x) not available in this release
 NA(y)    not available in this year
 NA(z)                  see codebook</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>gss2022<span class="sc">$</span>letin1a[<span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;labelled&lt;double&gt;[0]&gt;: number of immigrants nowadays should be

Labels:
 value                         label
     1               increased a lot
     2            increased a little
     3      remain the same as it is
     4              reduced a little
     5                 reduced a lot
 NA(d)                    don't know
 NA(i)                           iap
 NA(j)            I don't have a job
 NA(m)                   dk, na, iap
 NA(n)                     no answer
 NA(p)                 not imputable
 NA(q)                 not imputable
 NA(r)                       refused
 NA(s)                skipped on web
 NA(u)                    uncodeable
 NA(x) not available in this release
 NA(y)    not available in this year
 NA(z)                  see codebook</code></pre>
</div>
</div>
<p>Naive estimate for effect of <span class="math inline">\(T\)</span> (family’s income at 16 years old) on <span class="math inline">\(Y\)</span> (attitude about immigration reduction / increase):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>naive_data <span class="ot">&lt;-</span> gss2022 <span class="sc">|&gt;</span> <span class="fu">select</span>(letin1a, polviews) <span class="sc">|&gt;</span> haven<span class="sc">::</span><span class="fu">zap_labels</span>()</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>naive_m <span class="ot">&lt;-</span> <span class="fu">lm</span>(letin1a <span class="sc">~</span> polviews, <span class="at">data =</span> naive_data)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(naive_m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic   p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)    1.82     0.0535      34.1 1.18e-218
2 polviews       0.331    0.0125      26.5 1.52e-140</code></pre>
</div>
</div>
<p>Naively, looks like an increase of one point away from extremely liberal (1), towards extremely conservative (7) drives a .331 point movement away from immigration should be increased a lot (1) toward immigration should be reduced a lot (5).</p>
<p>Let’s look at the factor version of polviews, so we can see what the increase at each step is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>naive_m <span class="ot">&lt;-</span> <span class="fu">lm</span>(letin1a <span class="sc">~</span> <span class="fu">factor</span>(polviews), <span class="at">data =</span> naive_data)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(naive_m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 5
  term              estimate std.error statistic   p.value
  &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)          2.16     0.0803     26.9  3.31e-144
2 factor(polviews)2    0.240    0.0949      2.53 1.14e-  2
3 factor(polviews)3    0.659    0.0979      6.73 2.00e- 11
4 factor(polviews)4    1.04     0.0864     12.0  1.04e- 32
5 factor(polviews)5    1.29     0.0967     13.4  7.99e- 40
6 factor(polviews)6    1.68     0.0942     17.9  2.79e- 68
7 factor(polviews)7    1.76     0.119      14.8  7.00e- 48</code></pre>
</div>
</div>
<p>Wait. I smell… POLARIZATION</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>ests <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.2404295</span>, <span class="fl">0.6587506</span>, <span class="fl">1.0397810</span>, <span class="fl">1.2947305</span>, <span class="fl">1.6838993</span>, <span class="fl">1.7643468</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting vertical lines at each estimate value</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> ests, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span> </span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HW9_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Hmm. Kind of.</p>
</section>
<section id="section-1" class="level3">
<h3 class="anchored" data-anchor-id="section-1">9.1.2</h3>
<p>Think of possible confounding variables that might affect this estimate.</p>
<p>Draw a DAG</p>
<p><img src="images/clipboard-3162582392.png" class="img-fluid"></p>
<p>What is your estimand (ATE, ATT, ATU)?</p>
<blockquote class="blockquote">
<p>ATE. We infer that all people are at least a little “treated” by their given political attitudes, and that this has some generalized “treatment effect” on attitudes towards immigration.</p>
</blockquote>
</section>
<section id="section-2" class="level3">
<h3 class="anchored" data-anchor-id="section-2">9.1.3</h3>
<p>Select the appropriate covariates in the GSS that allow for causal identification.<br>
Make a note of any transformations.</p>
<ul>
<li>Parents’ education
<ul>
<li>PADEG, MADEG</li>
</ul></li>
<li>Parents / grandparents born in US
<ul>
<li>Binarized, 0 if one of the parents was not: PABORN/ MABORN</li>
<li>Binarized, 0 if one of the grandparents was not: GRANBORN</li>
</ul></li>
<li>Grew up in urban, suburban, or rural area
<ul>
<li>RES16</li>
</ul></li>
<li>Grew up in diverse / immigrant community
<ul>
<li>Instead, using current racial composition of neighborhood: RACLIVE</li>
</ul></li>
<li>Grew up in high / mid / low income family
<ul>
<li>INCOM16</li>
</ul></li>
<li>Respondent’s race
<ul>
<li>Binarized, 1 if nonwhite: RACE</li>
</ul></li>
<li>Respondent’s age
<ul>
<li>AGE</li>
</ul></li>
<li>Respondent’s political leaning
<ul>
<li>POLVIEWS</li>
</ul></li>
<li>Respondent’s education level
<ul>
<li>EDUC</li>
</ul></li>
<li>Respondent experienced unemployment
<ul>
<li>UNEMP</li>
</ul></li>
<li>Respondent’s religion
<ul>
<li>RELIG</li>
</ul></li>
<li>Respondent born in the US
<ul>
<li>Binarized, 0 if not born in the US: BORN</li>
</ul></li>
</ul>
<p>Are there any variables missing from the DAG you drew earlier?</p>
<blockquote class="blockquote">
<p>I couldn’t find a proxy for:</p>
<ul>
<li><p>parents’ political leaning</p></li>
<li><p>Clean variable for parents experiencing unemployment. Decided to use respondent unemployment instead, as also seems relavent</p></li>
<li><p>R’s media consumption / the portrayal of immigrants therein</p></li>
<li><p>Whether area R grew up in was diverse / immigrant community, so using self-reported diversity of current community because it also seems relavent</p></li>
</ul>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>d_r <span class="ot">&lt;-</span> gss2022 <span class="sc">|&gt;</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    letin1a, polviews,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    padeg, madeg, paborn, maborn,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    granborn, res16, raclive, race,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    ethnic, age, incom16, educ,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    unemp, relig, born</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> <span class="fu">drop_na</span>() <span class="sc">|&gt;</span> </span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">nonwhite =</span> <span class="fu">if_else</span>(race <span class="sc">==</span> <span class="dv">1</span>, 0L, 1L),</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">parents_born_us =</span> <span class="fu">if_else</span>(paborn <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> maborn <span class="sc">==</span> <span class="dv">1</span>, 1L, 0L),</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">grands_born_us =</span> <span class="fu">if_else</span>(granborn <span class="sc">==</span> <span class="dv">0</span>, 1L, 0L),</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">born_us =</span> <span class="fu">if_else</span>(born <span class="sc">==</span> <span class="dv">1</span>, 1L, 0L),</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">less_immigrants =</span> <span class="fu">if_else</span>(letin1a <span class="sc">&gt;</span> <span class="dv">3</span>, 1L, 0L) <span class="co"># binarized version, unused</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="section-3" class="level3">
<h3 class="anchored" data-anchor-id="section-3">9.1.4</h3>
<p>Using regression to get the effect of <code>incom16</code> on <code>letin1a</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>form <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(<span class="st">"letin1a ~ factor(polviews) + factor(padeg) + factor(madeg) +                        unemp + grands_born_us + factor(res16) + raclive + nonwhite + </span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="st">                   age + I(age^2) + factor(incom16) + educ + I(educ^2) + </span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="st">                   factor(relig) + born_us + parents_born_us"</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>form_cont_polviews <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(<span class="st">"letin1a ~ polviews + factor(padeg) + factor(madeg) + unemp + grands_born_us + factor(res16) + raclive + nonwhite + age + I(age^2) + factor(incom16) + educ + I(educ^2) + factor(relig) + born_us + parents_born_us"</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>m_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(form, <span class="at">data =</span> d_r)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>m_lm_cont_polviews <span class="ot">&lt;-</span> <span class="fu">lm</span>(form_cont_polviews, <span class="at">data =</span> d_r)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Checking out model, ATE:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(m_lm_cont_polviews, <span class="at">cof.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"polviews"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  term     estimate std.error statistic  p.value
  &lt;chr&gt;       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 polviews    0.308    0.0223      13.8 2.05e-40</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(m_lm, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 44 × 7
   term              estimate std.error statistic  p.value conf.low conf.high
   &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
 1 (Intercept)        1.36       0.548     2.48   1.31e- 2  0.286       2.44 
 2 factor(polviews)2  0.301      0.155     1.94   5.31e- 2 -0.00404     0.606
 3 factor(polviews)3  0.804      0.164     4.91   1.05e- 6  0.483       1.13 
 4 factor(polviews)4  1.13       0.148     7.63   4.86e-14  0.840       1.42 
 5 factor(polviews)5  1.23       0.163     7.54   9.23e-14  0.909       1.55 
 6 factor(polviews)6  1.63       0.160    10.2    2.95e-23  1.31        1.94 
 7 factor(polviews)7  1.87       0.199     9.36   3.90e-20  1.48        2.26 
 8 factor(padeg)1     0.123      0.0902    1.36   1.74e- 1 -0.0544      0.300
 9 factor(padeg)2    -0.00928    0.180    -0.0516 9.59e- 1 -0.362       0.344
10 factor(padeg)3     0.0299     0.122     0.244  8.07e- 1 -0.210       0.270
# ℹ 34 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">avg_slopes</span>(m_lm, <span class="at">variables =</span> <span class="st">"polviews"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `polviews` variable is treated as a categorical (factor) variable,
  but the original data is of class haven_labelled. It is safer and faster
  to convert such variables to factor before fitting the model and calling
  a `marginaleffects` function.
  
  This warning appears once per session.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Term Contrast Estimate Std. Error     z Pr(&gt;|z|)    S    2.5 % 97.5 %
 polviews    2 - 1    0.301      0.155  1.94   0.0529  4.2 -0.00372  0.605
 polviews    3 - 1    0.804      0.164  4.91   &lt;0.001 20.1  0.48316  1.126
 polviews    4 - 1    1.131      0.148  7.63   &lt;0.001 45.3  0.84068  1.422
 polviews    5 - 1    1.228      0.163  7.54   &lt;0.001 44.3  0.90892  1.547
 polviews    6 - 1    1.625      0.160 10.15   &lt;0.001 78.0  1.31158  1.939
 polviews    7 - 1    1.867      0.199  9.36   &lt;0.001 66.8  1.47612  2.258

Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high 
Type:  response </code></pre>
</div>
</div>
<p>Interesting - just gonna take a peek at how the POLARIZATIOn seems now.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>ests_r <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.01</span>, <span class="fl">0.301</span>, <span class="fl">0.804</span>, <span class="fl">1.131</span>, <span class="fl">1.228</span>, <span class="fl">1.625</span>, <span class="fl">1.867</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting vertical lines at each estimate value</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> ests, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span> </span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> ests_r, <span class="at">color =</span> <span class="st">"orange"</span>) <span class="sc">+</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HW9_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Interesting.</p>
</section>
<section id="section-4" class="level3">
<h3 class="anchored" data-anchor-id="section-4">9.1.5</h3>
<p>Try to achieve covariate balancing.</p>
<p><strong>CBPS</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>trt_form <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(<span class="st">"factor(polviews) ~ factor(padeg) + factor(madeg) +                                    unemp + grands_born_us + factor(res16) + raclive + nonwhite + </span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="st">                        age + I(age^2) + factor(incom16) + educ + I(educ^2) + </span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="st">                        factor(relig) + born_us + parents_born_us"</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>cbps_weights <span class="ot">&lt;-</span> <span class="fu">weightit</span>(trt_form, <span class="at">data =</span> d_r, <span class="at">method =</span> <span class="st">"cbps"</span>, </span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>                         <span class="at">estimand =</span> <span class="st">"ate"</span>, <span class="at">over =</span> <span class="cn">FALSE</span>)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cbps_weights)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Summary of weights

- Weight ranges:

     Min                                    Max
1 1.0359 |---------------------------| 133.0933
2 1.1931 |------|                       35.3666
3 1.9222 |--------|                     46.0801
4 1.0000 ||                             11.0568
5 1.7176 |----|                         29.3322
6 1.5594 |-----|                        31.0746
7 1.0306 |------------------------|    119.3078

- Units with the 5 most extreme weights by group:
                                           
       707    1154     490     915      362
 1  74.909 78.1905 81.8047 90.4496 133.0933
       187     880     877     215      950
 2 26.2466 26.4581 27.7331 35.3519  35.3666
       578     716     397     246      179
 3 22.8292 26.4125 29.8046 35.9556  46.0801
         4     963     281     380       35
 4  8.0047  8.0546   8.306  9.1738  11.0568
       158    1089     674    1065     1093
 5 21.1672 21.5134 21.6331 26.2829  29.3322
         9     630     903     409      261
 6 21.2774 22.5632 27.1158 28.2317  31.0746
       190    1043    1155     889     1124
 7 63.2006 63.9052 75.9125 83.4573 119.3078

- Weight statistics:

  Coef of Var   MAD Entropy # Zeros
1       1.204 0.831   0.546       0
2       0.931 0.645   0.319       0
3       0.718 0.496   0.205       0
4       0.444 0.319   0.085       0
5       0.654 0.465   0.178       0
6       0.884 0.623   0.291       0
7       1.104 0.828   0.527       0

- Effective Sample Sizes:

               1      2      3      4      5     6     7
Unweighted 65.   175.   130.   396.   163.   207.  61.  
Weighted   26.78  94.02  85.99 330.97 114.36 116.5 27.74</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">love.plot</span>(cbps_weights,</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">thresholds =</span> .<span class="dv">1</span>, <span class="at">stats =</span> <span class="fu">c</span>(<span class="st">"m"</span>,<span class="st">"ks"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Standardized mean differences and raw mean differences are present in the same plot. 
Use the `stars` argument to distinguish between them and appropriately label the x-axis.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="HW9_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>cbps_est_naive <span class="ot">&lt;-</span> <span class="fu">lm</span>(letin1a <span class="sc">~</span> polviews, <span class="at">data =</span> d_r, </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">weights =</span> cbps_weights<span class="sc">$</span>weights)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>cbps_est_naive_factor <span class="ot">&lt;-</span> <span class="fu">lm</span>(letin1a <span class="sc">~</span> <span class="fu">factor</span>(polviews), <span class="at">data =</span> d_r, </span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">weights =</span> cbps_weights<span class="sc">$</span>weights)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(cbps_est_naive, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term        estimate std.error statistic   p.value conf.low conf.high
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)    2.07     0.0720      28.8 8.18e-139    1.93      2.21 
2 polviews       0.263    0.0160      16.4 1.58e- 54    0.231     0.294</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(cbps_est_naive_factor, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 7
  term              estimate std.error statistic   p.value conf.low conf.high
  &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)         2.39      0.0822    29.1   9.38e-141    2.23      2.55 
2 factor(polviews)2   0.0472    0.122      0.388 6.98e-  1   -0.191     0.286
3 factor(polviews)3   0.476     0.120      3.96  8.00e-  5    0.240     0.712
4 factor(polviews)4   0.854     0.120      7.09  2.36e- 12    0.617     1.09 
5 factor(polviews)5   0.963     0.120      8.01  2.80e- 15    0.727     1.20 
6 factor(polviews)6   1.33      0.120     11.1   2.37e- 27    1.10      1.57 
7 factor(polviews)7   1.45      0.117     12.4   4.39e- 33    1.22      1.68 </code></pre>
</div>
</div>
<p>Crudely comparing to factor estimates from naive estimate again:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>ests_w <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.01</span>, <span class="fl">0.0471939</span>, <span class="fl">0.4757196</span>, <span class="fl">0.8537163</span>, <span class="fl">0.9625970</span>, <span class="fl">1.3347595</span>, <span class="fl">1.4498106</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting vertical lines at each estimate value</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> ests, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span> </span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> ests_w, <span class="at">color =</span> <span class="st">"magenta"</span>) <span class="sc">+</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HW9_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="section-5" class="level3">
<h3 class="anchored" data-anchor-id="section-5">9.1.6</h3>
<p>Combining weighting and regression, what is the effect of T on Y<em>?</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>m_robust <span class="ot">&lt;-</span> <span class="fu">lm</span>(form, <span class="at">data =</span> d_r, </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">weights =</span> cbps_weights<span class="sc">$</span>weights)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>m_robust_cont_polviews <span class="ot">&lt;-</span> <span class="fu">lm</span>(form_cont_polviews, <span class="at">data =</span> d_r, </span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>                             <span class="at">weights =</span> cbps_weights<span class="sc">$</span>weights)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(m_robust_cont_polviews, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"polviews"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 7
  term     estimate std.error statistic  p.value conf.low conf.high
  &lt;chr&gt;       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 polviews    0.253    0.0157      16.1 6.26e-53    0.222     0.284</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">avg_slopes</span>(m_robust, </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">variables =</span> <span class="st">"polviews"</span>, </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">wts =</span> cbps_weights<span class="sc">$</span>weights)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Term Contrast Estimate Std. Error      z Pr(&gt;|z|)     S  2.5 % 97.5 %
 polviews    2 - 1    0.035      0.117  0.299    0.765   0.4 -0.195  0.264
 polviews    3 - 1    0.470      0.116  4.061   &lt;0.001  14.3  0.243  0.697
 polviews    4 - 1    0.830      0.116  7.146   &lt;0.001  40.0  0.602  1.057
 polviews    5 - 1    0.933      0.116  8.042   &lt;0.001  50.0  0.705  1.160
 polviews    6 - 1    1.293      0.116 11.156   &lt;0.001  93.6  1.066  1.520
 polviews    7 - 1    1.382      0.116 11.951   &lt;0.001 107.0  1.155  1.609

Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high 
Type:  response </code></pre>
</div>
</div>
</section>
<section id="findings" class="level3">
<h3 class="anchored" data-anchor-id="findings"><strong>9.1.7 - Findings</strong></h3>
<p><em>“Write 3-5 paragraphs explaining your research question, the methods you used, and the answer you came up with.”</em></p>
<p>In this homework, I set out to find the impact of political leaning on immigration attitudes. To do this, I used data from the 2022 GSS, and adjusted for the impacts of potential confounding variables using weighting and regression. My hypothesis at the outset was that more conservative political attitudes would be associated with less enthusiasm towards immigration, and this was measurably true here.</p>
<p>The most apt treatment variable available was POLVIEWS, which allows respondents to self-report political inclination on a scale of 1 to 7, where 1 is extremely liberal, 4 is moderate, and 7 is extremely conservative. The outcome variable that fit best was LETIN1A, a 1 to 5 scale which captures respondents’ opinion on how the amount of immigration to the U.S. should change, where 1 is increase a lot, 3 is remain the same, and 5 is reduce a lot. A naive estimate given by a linear regression found that generally, every increase of 1 point in POLVIEWS (read, toward conservatism) resulted in a .331 point increase in LETIN1A (read, toward a immigration reduction stance).</p>
<p>I created a DAG to represent the potential confounding variables. I hoped to capture information about the respondents’ upbringing and current circumstances that would potentially impact their political leaning and / or their attitudes about immigration. This included variables related to family immigration history, childhood living circumstances, diversity of living area, education and income levels, race and ethnicity, and age (to capture generational cohort effects). The full list of variables selected to capture these factors is above.</p>
<p>Weights generated by the CBPS method in the WeightIt package allowed us to reduce the bias introduced by selection effects, and combination with a regression model over the selected confounders led to a more robust estimate of the relationship between POLVIEWS and LETIN1A. With weighting and correction, we find a .253 increase in LETIN1A for every 1 point increase in POLVIEWS, when POLVIEWS is viewed as continuous. However, allowing our analysis to be ordinal by using the factor version of POLVIEWS, we can see the more granular relative increase in LETIN1A for each value of POLVIEWS (see last output above). Across all analyses, and after correction for potential bias, the hypothesized positive relationship between conservatism and less enthusiasm towards immigration to the U.S. held.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>